Model
Fayob/blog_app pull request #1
Opened 2023-01-18 15:43 UTC by Fayob

The following was done in this milestone:

- project was set up with Postgres database.
- built project schema.
- created necessary migration files.
- table and column names match the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
- included Foreign keys.
- all columns that are foreign keys was indexed.

2023-01-18 16:52 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Favour, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
Commit messages are descriptive. :heavy_check_mark:
No linter errors. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 16:52 UTC, SajjadAhmad14 commented on db/migrate/20230118102123_create_post.rb
> +      t.string :text
Please use `text` data type for `text` attribute in posts table as it's mentioned here in this [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).

2023-01-18 16:52 UTC, SajjadAhmad14 commented on db/migrate/20230118102331_add_user_ref_to_posts.rb
> +    add_reference :posts, :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` in posts table as it's shown in the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). You may read [this](https://stackoverflow.com/questions/36227578/reference-with-custom-name-and-foreign-key) thread on stack overflow on how to add a custom foreign key in Rails.

2023-01-18 16:52 UTC, SajjadAhmad14 commented on db/migrate/20230118102756_create_like.rb
> +    add_reference :likes, :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` in likes table as it's shown in the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). You may read [this](https://stackoverflow.com/questions/36227578/reference-with-custom-name-and-foreign-key) thread on stack overflow on how to add a custom foreign key in Rails.

2023-01-18 16:52 UTC, SajjadAhmad14 commented on db/migrate/20230118102510_create_comment.rb
> +      t.string :text
Please use `text` data type for `text` attribute in comments table as it's mentioned here in this [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).

2023-01-18 16:52 UTC, SajjadAhmad14 commented on db/migrate/20230118102510_create_comment.rb
> +    add_reference :comments, :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` in comments table as it's shown in the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). You may read [this](https://stackoverflow.com/questions/36227578/reference-with-custom-name-and-foreign-key) thread on stack overflow on how to add a custom foreign key in Rails.

2023-01-19 12:12 UTC, ShadyShawkat approved these changes
## Hi @Fayob, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:18 UTC, merged